### ISSUE TITLE
Some random letters

### ISSUE THREAD

**Issue by stranothus** [knaagar/definitions-bookmarklet#1]
https://github.com/knaagar/definitions-bookmarklet/blob/864f64ea5ce8af3b5ea8b72ec5e9442744cb7678/public/scripts/script.js#L77

Looks like you accidentally added some random letters in one of your files. I didn't think it was significant enough for a a pull request, but it does make some annoying errors pop up in the console.

**Comment by knaagar** [comment]
Thank you for pointing that out. Removed.
